#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-openshift
Version  : 0.12.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/bf/61/395013f4378b12f4755522d50fc3649a774a1d6b1d95d4682bade4abeba1/openshift-0.12.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/bf/61/395013f4378b12f4755522d50fc3649a774a1d6b1d95d4682bade4abeba1/openshift-0.12.1.tar.gz
Summary  : OpenShift python client
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-openshift-bin = %{version}-%{release}
Requires: pypi-openshift-license = %{version}-%{release}
Requires: pypi-openshift-python = %{version}-%{release}
Requires: pypi-openshift-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jinja2)
BuildRequires : pypi(kubernetes)
BuildRequires : pypi(python_string_utils)
BuildRequires : pypi(ruamel.yaml)
BuildRequires : pypi(six)

%description
OpenShift python client
======================
[![Build Status](https://travis-ci.com/openshift/openshift-restclient-python.svg?branch=master)](https://travis-ci.com/openshift/openshift-restclient-python)
[![Coverage Status](https://coveralls.io/repos/github/openshift/openshift-restclient-python/badge.svg?branch=master)](https://coveralls.io/github/openshift/openshift-restclient-python?branch=master)

%package bin
Summary: bin components for the pypi-openshift package.
Group: Binaries
Requires: pypi-openshift-license = %{version}-%{release}

%description bin
bin components for the pypi-openshift package.


%package license
Summary: license components for the pypi-openshift package.
Group: Default

%description license
license components for the pypi-openshift package.


%package python
Summary: python components for the pypi-openshift package.
Group: Default
Requires: pypi-openshift-python3 = %{version}-%{release}

%description python
python components for the pypi-openshift package.


%package python3
Summary: python3 components for the pypi-openshift package.
Group: Default
Requires: python3-core
Provides: pypi(openshift)
Requires: pypi(jinja2)
Requires: pypi(kubernetes)
Requires: pypi(python_string_utils)
Requires: pypi(ruamel.yaml)
Requires: pypi(six)

%description python3
python3 components for the pypi-openshift package.


%prep
%setup -q -n openshift-0.12.1
cd %{_builddir}/openshift-0.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639061572
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-openshift
cp %{_builddir}/openshift-0.12.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-openshift/92170cdc034b2ff819323ff670d3b7266c8bffcd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/requirements.txt/requirements.txt

%files bin
%defattr(-,root,root,-)
/usr/bin/openshift-ansible-gen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-openshift/92170cdc034b2ff819323ff670d3b7266c8bffcd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
